// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVEhkbZ9J6tRT4Kv8qTb1SbJPBedKCHmE',
    appId: '1:755795938378:web:0451b0fbe851c52f9b2ab3',
    messagingSenderId: '755795938378',
    projectId: 'flutternew-c1eb4',
    authDomain: 'flutternew-c1eb4.firebaseapp.com',
    storageBucket: 'flutternew-c1eb4.firebasestorage.app',
    measurementId: 'G-4LZDR55FH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSJ-n2PexByg286H1eBhLpwhUIFPWs14',
    appId: '1:755795938378:android:502d3ad0b28ef6c99b2ab3',
    messagingSenderId: '755795938378',
    projectId: 'flutternew-c1eb4',
    storageBucket: 'flutternew-c1eb4.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELwN6-fiaWkn4lZ0Jav33dpNGVRf6rVg',
    appId: '1:755795938378:ios:088cf0b7c30224009b2ab3',
    messagingSenderId: '755795938378',
    projectId: 'flutternew-c1eb4',
    storageBucket: 'flutternew-c1eb4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAELwN6-fiaWkn4lZ0Jav33dpNGVRf6rVg',
    appId: '1:755795938378:ios:088cf0b7c30224009b2ab3',
    messagingSenderId: '755795938378',
    projectId: 'flutternew-c1eb4',
    storageBucket: 'flutternew-c1eb4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVEhkbZ9J6tRT4Kv8qTb1SbJPBedKCHmE',
    appId: '1:755795938378:web:03d4424f659dab3d9b2ab3',
    messagingSenderId: '755795938378',
    projectId: 'flutternew-c1eb4',
    authDomain: 'flutternew-c1eb4.firebaseapp.com',
    storageBucket: 'flutternew-c1eb4.firebasestorage.app',
    measurementId: 'G-F7EBTTS5P9',
  );
}
